(ns euler.problem12
  (:require [clojure.reflect :as r]
            [clojure.java.io :as io]
            [clojure.set :as set]
            [clojure.string :as str]
            [clojure.pprint :as pp]
            [clojure.edn :as edn]
            [clojure.test :as test]


            [criterium.core :as crit]
            [clj-http.client :as http]

            [clojure.inspector :refer [inspect inspect-table inspect-tree]]
            [clojure.tools.namespace.repl :refer [refresh refresh-all]]

            [flatland.useful.debug :refer [?]]
            [flatland.useful.map :refer [merge-in]]
            [flatland.useful.fn :refer [! validator as-fn thrush applied]]
            [flatland.useful.seq :as seq]
            [flatland.useful.utils :refer [verify returning pop-if queue let-later empty-coll? with-timing]]

            [euler.common :refer :all]
            )
)

"The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7
= 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?"

(defn solve [c]
  (time (first (filter #(<= c (divisor-count (second %))) triangle-numbers)))
  )

;; (solve 500)
;; "Elapsed time: 2987.214 msecs"
;; [12375 76576500]


;; posted solution:

(def count-factors divisor-count)

(defn ^long triangle500
  [^long target]
  (time
   (loop [i (int 3)]
     (let [vals (if (== 0 (rem i 2))
                  (* (count-factors (quot i 2))
                     (count-factors (+ i 1)))
                  (* (count-factors (quot (+ i 1) 2))
                     (count-factors i)))]
       (if (> vals target)
         (/ (* (+ i 1) i) 2)
         (recur (+ 1 i)))))))

;; "Elapsed time: 91.169 msecs"
;; 76576500
